# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CrT8sQnQms8FDqAyZaoClBULUyY1auC0

#Firstly, Importing necessary libraries
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd #data manipulation and analysis
import pandas as pd # for data manipulation and analysis
import numpy as np # for numerical,computing and statistical computation of the data
import matplotlib.pyplot as plt #for data visualization
# %matplotlib inline
import seaborn as sns #making visualization colorful
import scipy.stats as stats #statistical computation factors
from scipy.stats import f_oneway

"""#Loading the data"""

df =pd.read_csv("/content/Epi_Task_Data.csv")

df

"""#DATA OVERVIEW AND CLEANING"""

#allows you to see the top 10
df.head(10)

#allows you to see the bottom 10 just to check if there is consistency in the inputed data
df.tail(10)

#checking the data we are dealing with in terms of rows and colums
df.shape

"""there are 280 rows and 6 columns"""

df.info()

#viewing measures of central tendancy including all columns in the output even those withnull values
df.describe(include = "all")

#  #checking for the number of non-uniques values within the data in each column
df.nunique()

#checking for null values within the dataset
df.isna()

df.isna().sum()

"""#Computing a table showing mean ILI% per county per year"""

df.columns

#grouping the counties by year with their ili percentages in each county
#This shows the ili percentage per county per year
df.groupby (['year', 'county'])['ili_percentage'].mean()

sns.boxplot(data =df, x ='county', y='ili_percentage', hue='year', palette='Set3')
plt.title('ili_percentage across the counties per year')
plt.xlabel('County')
plt.ylabel('ILI Percentage')
plt.grid(True)
plt.tight_layout()
plt.show()

"""In 2023, all the counties ili_percentage was less than 5 except in Nakuru county where it was slightly above 5.In 2024, 4/7 counties had an ili% of 5 or above except Nairobi, Machakos and Kiambu. This means that in 2024, there was an increase in the total ili rates as compared to 2023.
In the two years combined, Kisumu and Nakuru counties have the highest ili rates while kiambu and Machakos have the lowest ili rates.
Research should be done to see why there was increase in ili rates from 2023 to 2024 and also what may be the cause of the different ili rates between the highest and lowest ili rates counties

WEEKLY ILI TRENDS ACROSS THE DIFFERENT COUNTIES
"""

df1=df[['county','epi_week', 'ili_percentage']]

#this shows a table(dataframe) the grouped data of the epi week trends across each county
df1

sns.boxplot(data =df1, x ='county', y='ili_percentage', hue='epi_week', palette='Set3')
plt.title('Weekly ILI Trends Across Counties')
plt.xlabel('County')
plt.ylabel('ILI Percentage')
plt.grid(True)
plt.tight_layout()
plt.show()

"""In Nairobi county, the weekly ili trend there was significant change with week 4 been the highest and week 5 recording the lowet rates
In Mombasa, week one recorded the highest ili rates and went on reducing through the following weeks and a significant increase in the 5th week.
In Kisumu, week one started on a low record and through week 2 and three the rates increased and later lowered in the 5th week.
Nakuru recorded a high ili rate on the first 3 weeks and reduced slightly but no significant change between the weeks.
Through the weeks, Machakos recorded a low rate below 5 apart from the 4th week which was slightly above 5.
Kiambu recorded the lowest rates betweenn the weeks with constant rates below 5 all through the weeks.
Kakamega ili rates started on a low rate went on increasing through the weeks upto a rate of 6% on the  third week.
"""

df.columns

"""CALCULATING THE INCIDENCE RATES PER 100,000 ACROSS 3 COUNTIES"""

#filtering the county variable to only show data of 3 counties which Nairobi, Nakuru, Mombasa which we will use to calculate their incidence rates
counties =['Nairobi', 'Mombasa', 'Nakuru']
df_filtered =df[df['county'].isin(counties)]
df_filtered

#incidence=(number of ili cases/population)*100000
#getting number of ili cases = ili_perecentage*population
estimated_ili_cases=(df_filtered['ili_percentage']/100)*df_filtered['population']
estimated_ili_cases

df_filtered['estimated_ili_cases'] = estimated_ili_cases
estimated_ili_cases

#grouping by county and year, them summing cases and population
summary=df_filtered.groupby(['county','year']).agg({'estimated_ili_cases':'sum','population':'sum'}).reset_index()
summary

#calculating incidence per 100,000
summary['incidence_per_100k']= (summary['estimated_ili_cases']/summary['population'])*100000
summary[['county', 'year', 'incidence_per_100k']]

#Visualizing the ili incidenece rates per 100k population across the 3 counties
sns.lineplot(data=summary, x='year', y='incidence_per_100k', hue='county')
plt.title('ILI Incidence Rates per 100k population Across selected Counties Over Time')
plt.xlabel('Year')
plt.ylabel('Incidence per 100,000')
plt.legend(title='County')
plt.grid(True)
plt.show()

"""The incidence rate per  100k in Nakuru increases through the years which explains the line graph shifting to the right unlike the plot of Mombasa and Nairobi which shifts to the left meaning that incidence rate per 100k decreased from the year 2023 to 2024

Using any statistical method to copare ili percentages across the three counties
"""

#seperate ili_percentage for each county
#first choose county
counties_2=['Machakos', 'Kisumu', 'Kakamega']
df_filtered_2 =df[df['county'].isin(counties_2)]
df_filtered_2

#seperating the ili perecentages for the 3 counties
machakos_ili =df_filtered_2[df_filtered_2['county'] =='Machakos']['ili_percentage']
kisumu_ili =df_filtered_2[df_filtered_2['county'] =='Kisumu']['ili_percentage']
kakamega_ili =df_filtered_2[df_filtered_2['county'] =='Kakamega']['ili_percentage']

#perform one-way Anova
f_statistic, p_value = f_oneway(machakos_ili, kisumu_ili, kakamega_ili)

#results of the one way Anova
print("F-statistic:", f_statistic)
print("P-value:", p_value)

if p_value < 0.05:
    print("There is a significant difference in ili percentages between the three counties.")
else:
    print("There is no significant difference in ili percentages between the three counties.")

#visualizing the differences in ili percentages between the three counties
sns.boxplot(data=df_filtered_2, x='county', y='ili_percentage', palette='Set2')
plt.title('Comparison of ILI Percentages Across Three Counties')
plt.xlabel('County')
plt.ylabel('ILI Percentage')
plt.grid(True, axis='y')
plt.tight_layout()
plt.show()

"""There is no significant difference in the ili percentages  of the three counties as the lowest can be seen at 4.2 and highest at 6.8 a different of 2.6 which is not quite significant.  Machakos has the lowest Ili percentages as compared to Kisumu and Kakamega with kakamega having the highest between the three counties. various resons may explain the results presented which may include the weather or location of the counties which may be a factor of the difference in the ili percentages between the counties.

"""